### ISSUE TITLE
cleanup the flood of revisions for the blog content type

### ISSUE THREAD

**Issue by mollux** [mautic/mautic.org-website#19]
Content of the the `blog` content type has an abnormal high number of revisions compares to other content types or to sane values in other sites.

Some nodes have up to 19K(!!) revisions, which results in a quite large database (specifically the `node_revision__body` table) compared the the number of nodes.

```
mysql> select type, count(*) from node_field_data group by type;
+--------------+----------+
| type         | count(*) |
+--------------+----------+
| blog         |      373 |
| event        |       19 |
| landing_page |       95 |
+--------------+----------+

mysql> select type, count(*) from node_field_revision r join node_field_data n on r.nid = n.nid group by type;
+--------------+----------+
| type         | count(*) |
+--------------+----------+
| blog         |   603943 |
| event        |       53 |
| landing_page |      985 |
+--------------+----------+

select nid, count(*) from node_field_revision group by nid order by count(*) desc limit 10;
+------+----------+
| nid  | count(*) |
+------+----------+
| 2621 |    19042 |
| 2631 |    18986 |
| 3101 |    17279 |
| 2821 |    14056 |
| 3086 |    13548 |
| 2776 |    13370 |
| 3231 |    12862 |
| 2706 |    12587 |
| 2686 |    11827 |
| 3411 |    10091 |
+------+----------+
```

The reason is a flaw in the `discourse_comments` module.
On every `build()` of the `discourse_comment_block`, the number of Discourse comments is [saved on the node](https://github.com/mautic/mautic.org-website/blob/50ecacd5efd710e2d4576f67c700065306114dc4/docroot/modules/custom/discourse_comments/src/Plugin/Block/DiscourseCommentBlock.php#L76), which generates a new revision AND invalidates all related cache tags (in this case `node_list`, `node_list:blog`). 

That block is only cacheable [for 15 minutes](https://github.com/mautic/mautic.org-website/blob/50ecacd5efd710e2d4576f67c700065306114dc4/docroot/modules/custom/discourse_comments/src/Plugin/Block/DiscourseCommentBlock.php#L119C21-L119C35), so both combined this is not at all ideal.

This specific code lead to outages on the live server, as as good as all pages were continuously invalidated due to visits to blog items with expired cache. The moment a crawler passed by the site, it could bring down the site.

We mitigated this issue on production by disabling that logic, but there should be a proper solution to:
* prevent storing the comments counter on the node, that's purely cached data to display
* cleanup the obsolete revisions

**Comment by lhridley** [comment]
@mollux There is a module (it is in "alpha" status but I'm currently testing it against a local environment, I'll let you know the outcome of testing as soon as the batch deletes finish running) that can be installed in production to limit the number of revisions that are kept on any node type:  https://www.drupal.org/project/node_revision_delete

**Comment by mollux** [comment]
@lhridley please hold, the issue is not only the revisions, and not all of them should be deleted.
I assigned the issue to me to prevent double work :) the cleanup process is running locally, but it will take a few hours.

**Comment by RCheesley** [comment]
I think this is dealt with now, can we close the issue/PR?
