### ISSUE TITLE
Website is offline, reporting a Drupal error

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic.org-website#7]
Hi folks,

Something seems to have gone wrong with the website, it's reporting the following Drupal error:

The website encountered an unexpected error. Please try again later.

Symfony\Component\Routing\Exception\RouteNotFoundException: Route "entity.path_alias.collection" does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName() (line 206 of core/lib/Drupal/Core/Routing/RouteProvider.php).

Please can someone address this with urgency @nick-vanpraet @mollux. Thanks!

**Comment by nick-vanpraet** [comment]
I cleared the caches which seems to have brough it back. No idea what caused it, the errors it was throwing were related to ancient drupal updates, still from Drupal 8's days. We didn't deploy anything on our end. Will investigate more tomorrow.

Site was luckily still mostly reachable for anonymous users, though the front page was pretty empty. Another mystery, you'd expect the error to be thrown there as well, but it only happened for logged in users.

**Comment by RCheesley** [comment]
Thanks for taking a look, indeed it's weird, the alert I got was just a content check I have which mails me once a day if the content on the homepage has changed! Our regular ping check had some wobbles in the early hours, but otherwise it was reporting as all OK.
